version: 2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.2-jessie-node
    steps:
      - checkout
      - restore_cache:
           key: npm_cache-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: npm_cache-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
